# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class P2pShare < Formula
  desc "A beautiful TUI for P2P file sharing"
  homepage "https://github.com/bivek7xdd/p2p-share"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bivek7xdd/p2p-share/releases/download/v1.0.4/p2p-share_1.0.4_darwin_amd64.tar.gz"
      sha256 "455b9cdb07f8f21414d28f98d3de2aaf422184e9bfdb72c2c3082a0bc4527a97"

      define_method(:install) do
        bin.install "p2p-share"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bivek7xdd/p2p-share/releases/download/v1.0.4/p2p-share_1.0.4_darwin_arm64.tar.gz"
      sha256 "b248796b94790f240d5ed32a9244e4796e96c37c0b3bb151b421b3c456f727dc"

      define_method(:install) do
        bin.install "p2p-share"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bivek7xdd/p2p-share/releases/download/v1.0.4/p2p-share_1.0.4_linux_amd64.tar.gz"
      sha256 "85cceddbf951b090cd14c9e630821e1df93642a5cefdc40a773c1d7979195baa"
      define_method(:install) do
        bin.install "p2p-share"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bivek7xdd/p2p-share/releases/download/v1.0.4/p2p-share_1.0.4_linux_arm64.tar.gz"
      sha256 "ac1eb25d383fcdcd380b14feeddc69dd71885ae9c375dfdefe32393da8032717"
      define_method(:install) do
        bin.install "p2p-share"
      end
    end
  end
end
